from pathlib import Path
import json,subprocess,collections
R=Path(__file__).resolve().parent;B=R.parent/'2026-09-18-340b960';rows=json.loads((B/'DEFECTS.json').read_text())
assert len(rows)==17 and sum(x['release_blocker'] for x in rows)==11
F='FIXED & VERIFIED';I='IMPLEMENTED, NOT VERIFIED';K='BLOCKED'
changes={
'D01':(F,'Удалено повышение роли по телефону/allowlist. Bound OTP, DB-admin + verified phone, audited grant/revoke, access/refresh rotation и отзыв. Все22 admin method/path защищены.','scripts/server/auth.ts scripts/server/security.ts scripts/server/admin-roles.ts scripts/app-server.ts src/hooks/useAuth.tsx','regression-suite.log http-security.json ui-flows.json','Реальный SMS и production incident/legacy-session review отдельно BLOCKED (EX-01/EX-04); исправление уязвимости подтверждено локально.'),
'D02':(F,'Адаптер читает фактический data envelope, сохраняет серверный ID и поля. Убраны fabricated local IDs. Проверена потеря201 ответа, restart/retry, один заказ, очистка корзины, история и повторное открытие.','src/lib/bazaar/adapters.ts src/lib/api/orders.ts src/lib/orders/checkoutAttempt.ts app/checkout/index.tsx src/hooks/useOrders.ts','regression-suite.log ui-flows.json screenshots/flow-order-confirmed.png screenshots/flow-order-reopened.png','Native end-to-end остаётся в исходной physical матрице BLOCKED.'),
'D03':(F,'Цена/название/остаток/филиал определяются серверными offers/branches в фиксированной организации. Quote до подтверждения, проверка актуальности, транзакционные holds, запрет подмены сумм и дробных/отрицательных количеств.','scripts/server/order-trust.ts scripts/server/orders.ts scripts/app-server.ts scripts/db/schema.sql src/lib/api/orders.ts app/checkout/index.tsx','regression-suite.log http-security.json ui-flows.json screenshots/flow-trusted-quote.png','Проверено на изолированном authoritative inventory fixture. Реальный POS/Bazaar adapter не подключён; production оформление не готово (EX-02).'),
'D04':(F,'Advisory transaction lock account+key сериализует одинаковые запросы; повторное чтение использует занятый DB client, без pool deadlock. Общий5xx ответ не раскрывает SQL.','scripts/server/orders.ts scripts/app-server.ts','regression-suite.log http-security.json','20 параллельных HTTP повторов:1×201+19×200, один ID и одна запись; ни одного5xx.'),
'D05':(F,'Сохраняется canonical request_hash. Новый payload под прежним ключом даёт409; прежний payload возвращает прежний заказ даже после изменения данных offers.','scripts/server/orders.ts scripts/db/schema.sql src/lib/orders/checkoutAttempt.ts','regression-suite.log http-security.json','Legacy request_hash=NULL не угадывается: конфликт и проверка истории.'),
'D06':(K,'Удаление UI/API/web: пароль, bound OTP, текущая версия deletion policy, реальные DELETE/отзыв сессий/media adapter; чужие операции сохраняются. Проверены rollback при ошибке media, остатки, receipts/returns/rewards/audit и web cleanup.','scripts/server/deletion.ts scripts/app-server.ts app/delete-account.tsx src/hooks/useAuth.tsx','regression-suite.log ui-flows.json screenshots/flow-deletion-confirmation.png screenshots/flow-deletion-complete.png','Нет утверждённой retention/deletion policy, реальных SMS/media/external-copy проверок и Android/iOS устройства. По исходной приёмке D06 нельзя закрыть только web.'),
'D07':(K,'Гостевые/profile/registration links и версионный reader privacy/terms/support реализованы. TEST тексты только в изолированной БД; юридические проекты вынесены отдельно.','app/legal/[kind].tsx src/components/LegalLinks.tsx scripts/server/documents.ts app/profile/about.tsx','gallery.json screenshots/guest-legal-privacy.png','Нужны утверждённые тексты, публичные URL, release network inventory и store privacy forms. TEST документ не является действующей policy.'),
'D08':(K,'Ссылки на правила до согласия; сервер требует текущие approved privacy/loyalty versions и сохраняет их вместе с согласием. Ставки/пороги/округление не изменены.','scripts/server/plumbers.ts scripts/server/documents.ts app/(auth)/register.tsx app/plumber/apply.tsx','regression-suite.log loyalty-existing.log gallery.json','Коммерческие правила и юридические условия не утверждены. Pilot settings/benefits не считаются согласованными; публикация/активация до согласования запрещена.'),
'D09':(K,'Исправлено5 ошибочных firm ID из6. Все6 внешних ссылок используют конкретный firm; адреса сверены по официальным страницам. Неутверждённые одинаковые часы убраны, общий телефон обозначен как поддержка.','src/data/stores.ts src/components/StoreCard.tsx src/components/maps/mapSource.ts','gallery.json screenshots/guest-maps.png','Нужно подтверждение владельцем адресов/контактов/часов и native внешнего перехода. Полная исходная приёмка пока не выполнена; источники в MAP_SOURCES.md.'),
'D10':(K,'Карта на всю ширину с фиксированным viewport, отдельный selector/card, timeout/retry/external fallback; атрибуция сохранена, перекрывающие элементы удалены.','src/components/maps/TwoGisMap.tsx src/components/maps/TwoGisMap.web.tsx app/(tabs)/maps/index.tsx','gallery.json screenshots/guest-maps.png screenshots/large-map.png','Внешний 2GIS widget продолжает обрезать popup на узком экране. Нужна поддерживаемая responsive SDK интеграция с предоставленным ключом/координатами; native жесты/геолокация/отказ не проверены. Это не FIXED.'),
'D11':(F,'Исправлен default limit1 из Number(null). Cursor pagination timestamp+ID без потери микросекунд, фильтры/сортировка сервера, infinite UI и Показать ещё.','scripts/app-server.ts scripts/server/loyalty.ts src/lib/api/program.ts src/hooks/useProgram.ts app/plumber/history.tsx','regression-suite.log http-security.json ui-flows.json screenshots/flow-ledger-last-page.png','137 реальных операций в тестовом ledger,5 страниц, нет повторов/потерь, сумма сверена с балансом. Production балансы не менялись.'),
'D12':(K,'Сокращён пустой image block, исправлен error fallback и contain; global catalog sorting/pagination проверены на137 fixtures. Реальные фото/описания не выдумывались.','src/components/ProductCard.tsx app/product/[id].tsx src/lib/bazaar/completeCatalog.ts src/lib/bazaar/client.ts','real-api-readonly.json regression-suite.log gallery.json','Повторный GET:50/50 товаров без фото/описания/категории/ненулевой цены; общий total2365, baseline2362. Нужны владелец каталога, доступ к source pipeline и утверждённая выборка SKU.'),
'D13':(F,'Увеличен контраст текста primary/muted/subtle/success/warning/danger; проверено12 значимых пар, минимальная из проверенных≥4.5:1.','src/constants/theme.ts src/components/AppInput.tsx src/components/AppButton.tsx','contrast.json gallery.json','Метод исходного критерия: расчёт токенов + web screenshots. Полные native large-font/TalkBack/VoiceOver проверки не закрыты.'),
'D14':(K,'URL inputs заменены системным picker/upload/preview/removal из формы. API проверяет размер/type и ownership. Defined media adapter требует decode/re-encode/EXIF cleanup и delete.','src/components/PhotoAttachment.tsx scripts/server/media.ts scripts/app-server.ts app/plumber/apply.tsx app/find-plumber/index.tsx','regression-suite.log gallery.json','Нет подключённого реального media storage/decoder и устройства для отказа/ограниченной библиотеки. Local fake adapter не подтверждает provider readiness.'),
'D15':(F,'Склонение бонусов целыми minor units, товаров/позиций и стажа; переводы notification/reward/profile статусов, реальный newline вместо literal\\n.','src/lib/programFormat.ts src/lib/formatters.ts src/components/OrderCard.tsx src/components/CategoryCard.tsx app/orders/[id].tsx app/(tabs)/catalog/index.tsx app/admin/index.tsx app/(tabs)/profile/index.tsx','regression-suite.log gallery.json screenshots/plumber-plumber-history.png','Проверены0/1/2/4/5/11/21/1.01 и видимые состояния; исходный метод CODE+WEB.'),
'D16':(I,'Одиночный системный picker без broad library request. Blocked media/storage/settings/overlay/audio; после анализа merged manifest также исключены unused biometric/vibration.','app.json app/image-search/index.tsx src/components/PhotoAttachment.tsx','android-aab-manifest.xml android-permissions.txt android-artifacts.json','Итоговый manifest/сборка проверены отдельно; выбор фото/camera denial/каталог на Android release device не выполнены. Не закрывать исходный критерий целиком.'),
'D17':(I,'Доверенный идентификатор — socket peer; произвольный X-Forwarded-For игнорируется. Атомарный общий DB rate limit переживает process restart и replicas.','scripts/server/security.ts scripts/app-server.ts scripts/db/schema.sql','http-security.json replica-rate-limit.json','Два локальных процесса + restart прошли. Исходная приёмка требует staging proxy/replicas; нет доступа. За reverse proxy требуется проверить общий IP bucket/capacity, а не снова доверять заголовку.')
}
for d in rows:
 status,change,files,evidence,limit=changes[d['id']];d['baseline_evidence']=d.pop('evidence');d.update(status=status,change=change,files=files.split(),verification=['evidence/'+p for p in evidence.split()],blocker=limit,baseline='2026-09-18-340b960')
 d['commits']=subprocess.check_output(['git','log','--format=%h','c88450a..HEAD','--',*d['files']],text=True).splitlines()
new=[
 ('D18','Другой rewardId под прежним ключом незаметно возвращал старую награду','Same clientRequestId, different rewardId returned the first redemption.','Другой rewardId →409;20 одинаковых повторов →один ID/одно списание.','Добавлена проверка reward_id до idempotent replay.',['scripts/server/loyalty.ts'],['evidence/D18-before.json','evidence/regression-suite.log'],'LOY'),
 ('D19','Состояния выбора не попадали в web accessibility API','При первом прогоне новый selector визуально закрывался, но aria-expanded отсутствовал; accessibilityState не переносится react-native-web0.21. Исходные radio/checkbox использовали тот же механизм.','Открытие/закрытие и checked состояния доступны в DOM; Escape сохраняет выбор.','Явные aria-expanded/checked/selected/busy/disabled; корректные radio semantics, подписи inputs.',['src/components/SelectField.tsx','src/components/AppInput.tsx','src/components/AppButton.tsx','app/checkout/index.tsx'],['evidence/ui-flows.json','evidence/screenshots/flow-select-search.png'],'A11Y'),
 ('D20','Параллельные изменения локальной корзины теряли количество','Реальный модуль baseline c88450a:20 одновременных add дают quantity1 вместо20.','20 add сохраняются; consume+add+replay вычитает отправленное один раз; clear ждёт предыдущие мутации.','Хранилище сериализует read-modify-write, cart/applied key сохраняются одним значением.',['src/lib/cart/cartStore.ts','src/lib/cart/localCart.ts','src/hooks/useAuth.tsx'],['evidence/D20-before.json','evidence/regression-suite.log'],'CORE'),
 ('D21','Отсутствующая API-конфигурация молча выбирала production','Baseline env module без EXPO_PUBLIC_API_URL возвращал production Railway URL. Ошибка имени переменной не останавливала подключение.','Без config URL пустой; production build gate отклоняет missing/http/test/debug config; embedded native URL проверен.','Удалён implicit production fallback; добавлен EAS pre-install/ручной validator и явные build endpoints.',['src/lib/config/env.ts','scripts/build/verify-env.cjs','package.json'],['evidence/release-env.json','evidence/android-artifacts.json'],'SEC')]
for i,title,actual,acceptance,change,files,evidence,domain in new:
 rows.append(dict(id=i,title=title,severity='P2',release_blocker=False,domain=domain,classification='NEW CONFIRMED DURING REMEDIATION',platform='Shared/client or local backend; scope stated in evidence',steps=actual,actual=actual,expected=acceptance,acceptance=acceptance,cause=actual,status=F,change=change,files=files,verification=evidence,blocker='Physical/staging gates outside the stated local/web method remain in CRITERIA.',baseline='new',commits=subprocess.check_output(['git','log','--format=%h','c88450a..HEAD','--',*files],text=True).splitlines()))
(R/'CLOSURE.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
lines=['# Реестр закрытия','', 'Исходные17 IDs и11 release_blocker flags сохранены. FIXED & VERIFIED применяется только при выполненной исходной приёмке указанным методом; native/staging требования не заменены web.7 исходных release blockers остаются незакрытыми.','', '|ID|Приоритет|Исходный release blocker|Статус|', '|---|---|---|---|']
for d in rows:lines.append(f"|{d['id']}|{d['severity']}|{'да' if d['release_blocker'] else 'нет'}|{d['status']}|")
for d in rows:
 lines += ['',f"## {d['id']} — {d['title']}",'',f"**{d['status']}**. Исходное поведение: {d['actual']}",'',f"Приёмка: {d['acceptance']}",'',f"Изменение: {d['change']}",'', 'Компоненты: '+', '.join('`'+p+'`' for p in d['files'])+'.','', 'Commits: '+', '.join(d['commits'])+'.','', 'Повторные проверки: '+', '.join(f'[{p}]({p})' for p in d['verification'])+'.','', 'Граница результата / препятствие: '+d['blocker']]
(R/'CLOSURE.md').write_text('\n'.join(lines)+'\n')
print(dict(original=collections.Counter(d['status'] for d in rows[:17]),original_blockers=collections.Counter(d['status'] for d in rows[:17] if d['release_blocker']),new=collections.Counter(d['status'] for d in rows[17:])))
