import {randomUUID} from 'node:crypto';
import {createAppOrder} from '../server/orders';
import {createServiceRequest,assignServiceRequest} from '../server/leads';
import assert from 'node:assert/strict';
import {createPool,ensureSchema} from '../server/db';
import {registerFixture,assertTestDatabase} from './fixtures';
import {deleteAccount} from '../server/deletion';
import {loginCustomer,requireSession,refreshSession} from '../server/auth';
import {createManualAdjustment,ingestReceipt,ingestReturn,redeemReward} from '../server/loyalty';
const pool=createPool(process.env.TEST_DATABASE_URL || '')!;const secret='isolated-delete-test';
async function main(){try{assertTestDatabase(pool);await ensureSchema(pool);
const phone=`+996704${String(Date.now()).slice(-6)}`;
const account=await registerFixture(pool,{name:'Delete test',phone,password:'test-password',accountType:'plumber',plumberApplication:{fullName:'Delete test',city:'Бишкек',workingDistricts:['Test'],specializations:['Test'],experienceYears:1,programConsent:true,dataProcessingConsent:true}},secret);
const id=account.user.id;const plumber=account.user.plumber!.id;
await pool.query("UPDATE app_plumber_profiles SET application_status='approved' WHERE id=$1",[plumber]);
await createManualAdjustment(pool,id,plumber,100,'Isolated deletion fixture');
const other=await registerFixture(pool,{name:'Other customer',phone:`+996780${String(Date.now()).slice(-6)}`,password:'test-password'},secret);
const branch=randomUUID();const org='deletion-fixture';
await pool.query("INSERT INTO app_order_branches(organization_id,id,name,address,is_active,orders_enabled) VALUES($1,$2,'Fixture','Fixture',true,true)",[org,branch]);
await pool.query("INSERT INTO app_order_offers(organization_id,branch_id,product_id,product_name,unit_price_minor,stock_quantity,is_active,valid_until) VALUES($1,$2,'sku','Fixture',100,10,true,now()+interval '1 hour')",[org,branch]);
const orderInput={clientRequestId:randomUUID(),customerName:'Fixture',customerPhone:phone,deliveryMethod:'pickup' as const,storeId:branch,storeName:null,storeAddress:null,deliveryAddress:null,comment:null,items:[{productId:'sku',productName:'Fixture',quantity:2,unitPrice:1,unitPriceLabel:null}]};
await createAppOrder(pool,id,orderInput,{organizationId:org});const otherOrder=await createAppOrder(pool,other.user.id,{...orderInput,clientRequestId:randomUUID()},{organizationId:org});
const lead=await createServiceRequest(pool,other.user.id,{serviceType:'Test',description:'Fixture service request',district:'Test',phone:other.user.phone,consentToShare:true});await assignServiceRequest(pool,other.user.id,lead.id,plumber);
const ext=randomUUID();const receipt=await ingestReceipt(pool,{externalReceiptId:ext,receiptNumber:'Fixture',storeId:branch,storeName:'Fixture',plumberIdentifier:account.user.plumber!.loyaltyCode,totalMinor:'100000',purchaseAt:new Date().toISOString(),source:'fixture',items:[{externalLineId:'line',productName:'Fixture',quantityMilli:'1000',unitPriceMinor:'100000',lineTotalMinor:'100000'}]},other.user.id);
const returned=await ingestReturn(pool,{externalReturnId:randomUUID(),externalReceiptId:ext,returnAt:new Date().toISOString(),source:'fixture',items:[{externalLineId:'line',quantityMilli:'500',amountMinor:'50000'}]},other.user.id);
const reward=randomUUID();await pool.query("INSERT INTO app_rewards(id,title,description,cost_minor,availability_count) VALUES($1,'Fixture','Fixture',50,2)",[reward]);await redeemReward(pool,id,reward,randomUUID());
const mediaId=randomUUID();await pool.query('INSERT INTO app_uploaded_media(id,account_id,provider_id,url) VALUES($1,$2,$1,$3)',[mediaId,id,'https://media.fixture.invalid/'+mediaId]);let removed='';const media={upload:async()=>{throw Error('unused');},remove:async(asset:string)=>{removed=asset;}};
const policy={mode:'erase-all',version:'fixture-v1'};
await assert.rejects(()=>deleteAccount(pool,id,'wrong',policy),(e:any)=>e.statusCode===401);
await assert.rejects(()=>deleteAccount(pool,id,'test-password',{mode:'',version:''}),(e:any)=>e.statusCode===503);
await assert.rejects(()=>deleteAccount(pool,id,'test-password',policy,{...media,remove:async()=>{throw Error('fixture media unavailable');}}),/fixture media unavailable/);
assert.equal(Number((await pool.query('SELECT count(*) FROM app_customers WHERE id=$1',[id])).rows[0].count),1);
assert.equal(Number((await pool.query('SELECT count(*) FROM app_orders WHERE customer_id=$1',[id])).rows[0].count),1);
assert.equal(Number((await pool.query('SELECT reserved_quantity FROM app_order_offers WHERE organization_id=$1 AND branch_id=$2',[org,branch])).rows[0].reserved_quantity),4);
assert.equal((await deleteAccount(pool,id,'test-password',policy,media)).deleted,true);
await assert.rejects(()=>requireSession(pool,account.session.accessToken,secret),(e:any)=>e.statusCode===401);
await assert.rejects(()=>refreshSession(pool,account.session.refreshToken,secret),(e:any)=>e.statusCode===401);
await assert.rejects(()=>loginCustomer(pool,{phone,password:'test-password'},secret),(e:any)=>e.statusCode===401);
for(const [table,column,value] of [['app_customers','id',id],['app_sessions','account_id',id],['app_plumber_profiles','id',plumber],['app_loyalty_transactions','plumber_id',plumber],['app_admin_audit_log','actor_id',id],['app_phone_challenges','phone',phone]])assert.equal(Number((await pool.query(`SELECT COUNT(*) FROM ${table} WHERE ${column}=$1`,[value])).rows[0].count),0);
assert.equal(removed,mediaId);
assert.equal(Number((await pool.query('SELECT reserved_quantity FROM app_order_offers WHERE organization_id=$1 AND branch_id=$2',[org,branch])).rows[0].reserved_quantity),2);
assert.equal(Number((await pool.query('SELECT count(*) FROM app_orders WHERE id=$1',[otherOrder.order!.id])).rows[0].count),1);
assert.equal((await pool.query('SELECT assigned_plumber_id FROM app_service_requests WHERE id=$1',[lead.id])).rows[0].assigned_plumber_id,null);
assert.equal(Number((await pool.query('SELECT availability_count FROM app_rewards WHERE id=$1',[reward])).rows[0].availability_count),2);
assert.equal(Number((await pool.query('SELECT count(*) FROM app_uploaded_media WHERE account_id=$1',[id])).rows[0].count),0);
assert.equal(Number((await pool.query("SELECT count(*) FROM app_admin_audit_log WHERE entity_id=ANY($1::text[])",[[(receipt.receipt as {id:string}).id,returned.returnId]])).rows[0].count),0);
assert.equal(Number((await pool.query("SELECT count(*) FROM app_service_request_events WHERE metadata::text LIKE $1",['%'+plumber+'%'])).rows[0].count),0);
console.log(JSON.stringify({suite:'deletion',assertions:24,status:'PASS',scope:'app database; external providers and retention approval remain blocked'}));
}finally{await pool.end();}}
void main().catch(e=>{console.error(e);process.exitCode=1;});
