import {spawn} from 'node:child_process';import {readFileSync,writeFileSync} from 'node:fs';import {setTimeout as wait} from 'node:timers/promises';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import pg from 'pg';
const database=process.env.TEST_DATABASE_URL;if(database!=='postgresql://audit@127.0.0.1:55448/remediation')throw new Error('Isolated database required');
const pool=new pg.Pool({connectionString:database});const sessions=JSON.parse(readFileSync('/private/tmp/avantehnik-remediation-sessions.json'));const account=sessions.plumber.user.id,plumber=sessions.plumber.user.plumber.id,reward=randomUUID();
await pool.query("INSERT INTO app_rewards(id,title,description,cost_minor,availability_count) VALUES($1,'Проверка восстановления','Изолированная проверка потери ответа',3000,1)",[reward]);
const out='docs/production-readiness/2026-09-18-followup/evidence';const checks=[];let lost=false;
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-first-run','--disable-background-networking','--remote-debugging-port=9362','--user-data-dir=/private/tmp/avantehnik-reward-browser','about:blank'],{stdio:'ignore'});
let targets;for(let n=0;n<60;n++){try{targets=await(await fetch('http://127.0.0.1:9362/json/list')).json();break;}catch{}await wait(250);}
const ws=new WebSocket(targets.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();
const send=(method,params={})=>new Promise(r=>{const n=++id;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}));});
ws.addEventListener('message',async e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}else if(m.method==='Fetch.requestPaused'){if(!lost&&m.params.responseStatusCode===201){lost=true;await send('Fetch.failRequest',{requestId:m.params.requestId,errorReason:'ConnectionClosed'});}else await send('Fetch.continueRequest',{requestId:m.params.requestId});}});
const ev=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.result?.value;
const body=()=>ev('document.body.innerText');const click=t=>ev(`Array.from(document.querySelectorAll('[role="button"],button')).find(x=>x.innerText.trim()===${JSON.stringify(t)})?.click()`);
async function until(f,label){for(let n=0;n<80;n++){if(await f())return;await wait(150);}throw new Error('Timeout: '+label+' '+await body());}
async function nav(path){await send('Page.navigate',{url:'http://127.0.0.1:8090'+path});await wait(700);}
async function shot(name){const s=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(out+'/screenshots/'+name+'.png',Buffer.from(s.result.data,'base64'));}
const count=async()=>Number((await pool.query('SELECT count(*) FROM app_reward_redemptions WHERE plumber_id=$1 AND reward_id=$2',[plumber,reward])).rows[0].count);
try{
 await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await nav('/welcome');await ev(`localStorage.setItem('avantehnik.app-session.v1',${JSON.stringify(JSON.stringify(sessions.plumber))})`);await nav('/plumber/rewards');await until(async()=>(await body()).includes('Проверка восстановления'),'rewards');
 await ev(`Array.from(document.querySelectorAll('[role="button"]')).find(x=>x.innerText.trim()==='Обменять бонусы'&&x.parentElement.innerText.includes('Проверка восстановления')).click()`);await until(async()=>(await body()).includes('Подтвердить обмен'),'confirmation');await shot('reward-confirm');
 await send('Fetch.enable',{patterns:[{urlPattern:'http://127.0.0.1:8789/plumber/rewards/'+reward+'/redeem',requestStage:'Response'}]});await click('Подтвердить обмен');await until(async()=>lost&&(await body()).includes('Проверить результат'),'lost ACK');assert.equal(await count(),1);checks.push('Lost 201: exactly one DB redemption');await shot('reward-lost-ack');
 await send('Fetch.disable');await nav('/plumber/rewards');await until(async()=>(await body()).includes('Проверить результат'),'persistent recovery');await click('Проверить результат');await until(async()=>(await body()).includes('Заявка создана'),'receipt');assert.equal(await count(),1);checks.push('Reload, unavailable reward, retry: one redemption');await shot('reward-recovered');
 const rows=await pool.query('SELECT id FROM app_reward_redemptions WHERE plumber_id=$1 AND reward_id=$2',[plumber,reward]);const ledger=await pool.query('SELECT amount_minor FROM app_loyalty_transactions WHERE reward_redemption_id=$1',[rows.rows[0].id]);assert.equal(ledger.rowCount,1);assert.equal(String(ledger.rows[0].amount_minor),'-3000');checks.push('Exactly one ledger debit of 3000');
 await nav('/plumber/rewards');await until(async()=>(await body()).includes('Заявка создана'),'accepted result persists');assert.ok((await body()).includes(rows.rows[0].id));checks.push('Accepted receipt survives another reload');
 await ev(`localStorage.setItem('avantehnik.app-session.v1',${JSON.stringify(JSON.stringify(sessions.customer))})`);await nav('/plumber/rewards');await until(async()=>(await body()).includes('Награды недоступны'),'account isolation');assert.ok(!(await body()).includes(rows.rows[0].id));checks.push('Other account cannot see receipt');
 await ev(`localStorage.setItem('avantehnik.app-session.v1',${JSON.stringify(JSON.stringify(sessions.plumber))})`);await nav('/plumber/rewards');await until(async()=>(await body()).includes('Понятно'),'original account');await click('Понятно');await until(async()=>await ev(`localStorage.getItem('avantehnik.reward-attempt.${account}')===null`),'acknowledged');checks.push('Only explicit acknowledgment clears attempt');console.log('PASS',checks);
}finally{writeFileSync(out+'/reward-ui.json',JSON.stringify({checks,lost,serverOperations:await count(),source:'WEB export + actual isolated API/PostgreSQL; network response deliberately dropped'},null,2));ws.close();chrome.kill('SIGTERM');await pool.end();}
