import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {createPool,ensureSchema} from '../server/db';
import {assertTestDatabase,registerFixture} from './fixtures';
import {registerCustomer,loginCustomer,updateCustomerProfile,hasAdminAccess,requireSession,refreshSession,revokeSession} from '../server/auth';
import {setAdministrator} from '../server/admin-roles';
import {rateLimit} from '../server/security';
import {requestAccountRecovery,listAccountRecovery,approveAccountRecovery,completeAccountRecovery} from '../server/account-recovery';
const pool=createPool(process.env.TEST_DATABASE_URL || '')!;const secret='isolated-security-test';const suffix=String(Date.now()).slice(-6);
let assertions=0;
const eq=(a:unknown,b:unknown)=>{assert.deepEqual(a,b);assertions++;};
async function rejects(fn:()=>Promise<unknown>,status:number){await assert.rejects(fn,(e:any)=>e.statusCode===status);assertions++;}
async function main(){try{
  assertTestDatabase(pool);await ensureSchema(pool);
  const phone=`+996700${suffix}`,otherPhone=`+996701${suffix}`;
  const account=await registerCustomer(pool,{name:'No SMS test',phone,password:'test-password'},secret,[phone]);const id=account.user.id;
  eq(account.user.isAdmin,false);eq(await hasAdminAccess(pool,id,[phone]),false);
  eq((await pool.query('SELECT phone_verified_at FROM app_customers WHERE id=$1',[id])).rows[0].phone_verified_at,null);
  eq(await requireSession(pool,account.session.accessToken,secret),id);
  eq((await loginCustomer(pool,{phone,password:'test-password'},secret)).user.id,id);
  await rejects(()=>registerCustomer(pool,{name:'Duplicate',phone,password:'other-password'},secret),409);
  await rejects(()=>loginCustomer(pool,{phone,password:'wrong'},secret),401);
  await rejects(()=>updateCustomerProfile(pool,id,{name:'Test',phone:otherPhone},[otherPhone]),401);
  await rejects(()=>updateCustomerProfile(pool,id,{name:'Test',phone:otherPhone,password:'wrong'},[otherPhone]),401);
  const changed=await updateCustomerProfile(pool,id,{name:'Test',phone:otherPhone,password:'test-password'},[otherPhone]);
  eq(changed.user.isAdmin,false);eq(await hasAdminAccess(pool,id,[otherPhone]),false);
  await rejects(()=>requireSession(pool,account.session.accessToken,secret),401);
  await rejects(()=>refreshSession(pool,account.session.refreshToken,secret),401);
  const signedIn=await loginCustomer(pool,{phone:otherPhone,password:'test-password'},secret);
  const rotated=await refreshSession(pool,signedIn.session.refreshToken,secret);
  eq(rotated.user.id,id);await rejects(()=>refreshSession(pool,signedIn.session.refreshToken,secret),401);
  await rejects(()=>requireSession(pool,signedIn.session.accessToken,secret),401);
  await revokeSession(pool,rotated.session.accessToken,secret);await rejects(()=>requireSession(pool,rotated.session.accessToken,secret),401);
  const admin=await registerFixture(pool,{name:'Fixture admin',phone:`+996702${suffix}`,password:'admin-password'},secret);
  await rejects(()=>setAdministrator(pool,id,admin.user.id,true,'fixture ticket'),403);
  // Isolated fixture bootstrap represents the trusted, reviewed server operator.
  await pool.query("INSERT INTO app_account_roles(account_id,role) VALUES($1,'admin')",[admin.user.id]);
  await setAdministrator(pool,admin.user.id,id,true,'verified employee case');eq(await hasAdminAccess(pool,id),true);
  const elevated=await loginCustomer(pool,{phone:otherPhone,password:'test-password'},secret);
  await setAdministrator(pool,admin.user.id,id,false,'revocation case');eq(await hasAdminAccess(pool,id),false);
  await rejects(()=>refreshSession(pool,elevated.session.refreshToken,secret),401);
  await rejects(()=>requireSession(pool,elevated.session.accessToken,secret),401);
  const regular=await loginCustomer(pool,{phone:otherPhone,password:'test-password'},secret);
  eq(regular.user.isAdmin,false);
  const known=await requestAccountRecovery(pool,otherPhone,'Fixture contact');const unknown=await requestAccountRecovery(pool,`+996703${suffix}`,'Fixture contact');eq(known,unknown);
  await requestAccountRecovery(pool,otherPhone,'Repeat contact');eq(Number((await pool.query("SELECT count(*) FROM app_account_recovery WHERE account_id=$1 AND status='pending'",[id])).rows[0].count),1);
  await rejects(()=>listAccountRecovery(pool,id),403);
  const request=(await listAccountRecovery(pool,admin.user.id)).find(r=>r.phone===otherPhone)!;assert.ok(request);assertions++;
  await rejects(()=>approveAccountRecovery(pool,id,request.id,'test-password','Fixture identity checked'),403);
  await rejects(()=>approveAccountRecovery(pool,admin.user.id,request.id,'wrong','Fixture identity checked'),401);
  await rejects(()=>approveAccountRecovery(pool,admin.user.id,request.id,'admin-password',''),400);
  const link=await approveAccountRecovery(pool,admin.user.id,request.id,'admin-password','Fixture identity checked');const token=new URL(link.url).searchParams.get('token')!;
  const stored=(await pool.query('SELECT token_hash FROM app_account_recovery WHERE id=$1',[request.id])).rows[0].token_hash;assert.ok(stored&&!stored.includes(token));assertions++;
  await rejects(()=>approveAccountRecovery(pool,admin.user.id,request.id,'admin-password','Repeated approval attempt'),409);
  await rejects(()=>completeAccountRecovery(pool,'invalid','new-password'),400);
  await rejects(()=>completeAccountRecovery(pool,token,'short'),400);
  const both=await Promise.allSettled([completeAccountRecovery(pool,token,'new-password'),completeAccountRecovery(pool,token,'new-password'),refreshSession(pool,regular.session.refreshToken,secret)]);
  const results=both.slice(0,2);
  eq(results.filter(r=>r.status==='fulfilled').length,1);eq(results.filter(r=>r.status==='rejected').length,1);
  const concurrentRefresh=both[2];
  if(concurrentRefresh.status==='fulfilled' && 'session' in concurrentRefresh.value) await rejects(()=>requireSession(pool,concurrentRefresh.value.session.accessToken,secret),401);
  else {eq(concurrentRefresh.status,'rejected');if(concurrentRefresh.status==='rejected')eq(concurrentRefresh.reason.statusCode,401);}
  await rejects(()=>completeAccountRecovery(pool,token,'another-password'),400);
  await rejects(()=>loginCustomer(pool,{phone:otherPhone,password:'test-password'},secret),401);
  eq((await loginCustomer(pool,{phone:otherPhone,password:'new-password'},secret)).user.id,id);
  await rejects(()=>requireSession(pool,regular.session.accessToken,secret),401);
  await rejects(()=>refreshSession(pool,regular.session.refreshToken,secret),401);
  await requestAccountRecovery(pool,otherPhone,'Fixture second request');const second=(await listAccountRecovery(pool,admin.user.id)).find(r=>r.phone===otherPhone&&r.status==='pending')!;
  const expiredLink=await approveAccountRecovery(pool,admin.user.id,second.id,'admin-password','Fixture expiration test');
  await pool.query("UPDATE app_account_recovery SET token_expires_at=now()-interval '1 second' WHERE id=$1",[second.id]);
  await rejects(()=>completeAccountRecovery(pool,new URL(expiredLink.url).searchParams.get('token')!,'new-password'),400);
  const fresh=await loginCustomer(pool,{phone:otherPhone,password:'new-password'},secret);
  const payload=JSON.parse(Buffer.from(fresh.session.accessToken.split('.')[0],'base64url').toString());payload.exp=0;const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url');
  await rejects(()=>requireSession(pool,encoded+'.'+createHmac('sha256',secret).update(encoded).digest('base64url'),secret),401);
  await rejects(()=>requireSession(pool,fresh.session.accessToken+'.',secret),401);
  const legacy=Buffer.from(JSON.stringify({sub:id,role:'admin',phone:otherPhone,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');
  await rejects(()=>requireSession(pool,legacy+'.'+createHmac('sha256',secret).update(legacy).digest('base64url'),secret),401);
  const limiter=randomUUID();await rateLimit(pool,'test',limiter,2,60_000);await rateLimit(pool,'test',limiter,2,60_000);await rejects(()=>rateLimit(pool,'test',limiter,2,60_000),429);
  console.log(JSON.stringify({suite:'no-sms-auth-and-manual-recovery',assertions,status:'PASS',externalTraffic:'none',scope:'local DB; human identity procedure still requires owner approval'}));
}finally{await pool.end();}}
void main().catch(e=>{console.error(e);process.exitCode=1;});
