import AsyncStorage from '@react-native-async-storage/async-storage';
import {createCartStore} from './cartStore';
const cart=createCartStore(AsyncStorage);
export const getLocalCartItems=cart.getItems;
export const setLocalCartItems=cart.setItems;
export const addLocalCartItem=cart.add;
export const updateLocalCartItemQuantity=cart.updateQuantity;
export const removeLocalCartItem=cart.remove;
export const clearLocalCart=cart.clear;
export const consumeSubmittedCart=cart.consume;
